@Host=http://localhost:5189
@ThreadId=123

###

POST {{Host}}/chat/{{ThreadId}}
Content-Type: application/json

[{
  "role": { "label": "User" },
  "items": [{
    "$type": "TextContent",
    "Text": "Hello!"
  }]
},{
  "role": { "label": "Assistant" },
  "items": [{
    "$type": "TextContent",
    "Text": "Hello, what can I do for you?"
  }]
}]

###

GET {{Host}}/chat/{{ThreadId}}

###

POST {{Host}}/chat/{{ThreadId}}/run